-- introducing new column to store tracked_file property
ALTER TABLE HARVEST_SOURCE ADD COLUMN TRACKED_FILE ENUM('Y','N') DEFAULT 'N' AFTER URL;
UPDATE HARVEST_SOURCE SET TRACKED_FILE='Y' WHERE TYPE='tracked_file';
--dropping obsolete values
ALTER TABLE HARVEST_SOURCE DROP COLUMN TYPE;
ALTER TABLE HARVEST_SOURCE DROP COLUMN NAME;
ALTER TABLE HARVEST_SOURCE DROP COLUMN CREATOR;