-- adding new column
ALTER TABLE HARVEST_SOURCE ADD COLUMN LAST_HARVEST_FAILED ENUM('Y','N') NOT NULL DEFAULT 'N';
-- migrating data
UPDATE HARVEST_SOURCE SET LAST_HARVEST_FAILED = 'Y' WHERE HARVEST_SOURCE_ID IN 
	(SELECT HARVEST_SOURCE_ID FROM HARVEST WHERE HARVEST_ID IN 
		(SELECT HARVEST_ID FROM HARVEST_MESSAGE WHERE TYPE IN ('ftl', 'err', 'wrn')));
